from typing import TypedDict, List, Annotated

from langchain_core.documents import Document

from langchain_core.messages import BaseMessage

from langgraph.graph.message import add_messages


class GraphState(TypedDict):
    """
    Shared state passed between all LangGraph nodes.
    """
    messages: Annotated[list[BaseMessage], add_messages]

    # User's question
    standalone_question: str

    # Route selected by the router agent
    route: str

    agent: str

    pages: list[int]

    # Retrieved documents (used by the RAG agent)
    documents: List[Document]

    # Display the retrieved context
    context: str

    # Image URLs (used by the Web agent for image requests)
    images: List[str]

    # Final response generated by the selected agent
    answer: str